# Generated by Django 6.0.4 on 2026-04-24 03:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0001_initial'),
        ('specifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAnalysisRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('request_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor Permintaan')),
                ('sample_description', models.TextField(verbose_name='Deskripsi Sampel')),
                ('requested_parameters', models.TextField(blank=True, verbose_name='Parameter yang Diminta')),
                ('external_lab', models.CharField(max_length=200, verbose_name='Nama Lab Eksternal')),
                ('lab_contact', models.CharField(blank=True, max_length=200, verbose_name='Kontak Lab')),
                ('lab_address', models.TextField(blank=True, verbose_name='Alamat Lab')),
                ('status', models.CharField(choices=[('submitted', 'Dikirim'), ('in_progress', 'Sedang Diproses'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='submitted', max_length=15, verbose_name='Status')),
                ('sent_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Pengiriman')),
                ('expected_completion', models.DateField(blank=True, null=True, verbose_name='Perkiraan Selesai')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('lab_report_number', models.CharField(blank=True, max_length=100, verbose_name='Nomor Laporan Lab')),
                ('lab_report_file', models.FileField(blank=True, null=True, upload_to='external_reports/', verbose_name='File Laporan Lab')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('related_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_requests', to='samples.sample', verbose_name='Sampel Terkait')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui Oleh')),
            ],
            options={
                'verbose_name': 'Permintaan Analisis Eksternal',
                'verbose_name_plural': 'Permintaan Analisis Eksternal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalAnalysisResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(max_length=200, verbose_name='Nama Parameter')),
                ('method', models.CharField(blank=True, max_length=200, verbose_name='Metode Uji')),
                ('result_value', models.CharField(max_length=200, verbose_name='Nilai Hasil')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Satuan')),
                ('spec_requirement', models.CharField(blank=True, max_length=200, verbose_name='Persyaratan Spesifikasi')),
                ('pass_fail', models.CharField(blank=True, max_length=10, verbose_name='Pass/Fail')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Input')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Diinput Oleh')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='external_requests.externalanalysisrequest', verbose_name='Permintaan')),
            ],
            options={
                'verbose_name': 'Hasil Analisis Eksternal',
                'verbose_name_plural': 'Hasil Analisis Eksternal',
                'ordering': ['request', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProductDevelopmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('request_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor Permintaan')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nama Produk')),
                ('product_type', models.CharField(choices=[('margarine', 'Margarin'), ('shortening', 'Shortening'), ('cooking_oil', 'Minyak Goreng'), ('other', 'Lainnya')], default='margarine', max_length=15, verbose_name='Tipe Produk')),
                ('description', models.TextField(verbose_name='Deskripsi & Tujuan')),
                ('target_smp_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Target SMP Min (°C)')),
                ('target_smp_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Target SMP Max (°C)')),
                ('target_iv_min', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Target IV Min')),
                ('target_iv_max', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Target IV Max')),
                ('target_spec_notes', models.TextField(blank=True, verbose_name='Catatan Target Spesifikasi')),
                ('target_packaging', models.CharField(blank=True, max_length=100, verbose_name='Target Kemasan')),
                ('status', models.CharField(choices=[('submitted', 'Diajukan'), ('in_progress', 'Sedang Dikerjakan'), ('trial', 'Dalam Percobaan'), ('completed', 'Selesai'), ('rejected', 'Ditolak'), ('on_hold', 'Ditahan')], default='submitted', max_length=15, verbose_name='Status')),
                ('priority', models.CharField(blank=True, max_length=10, verbose_name='Prioritas')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('final_formula_notes', models.TextField(blank=True, verbose_name='Catatan Formula Final')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('related_spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_requests', to='specifications.productspecification', verbose_name='Spesifikasi yang Dihasilkan')),
                ('rnd_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rnd_projects', to=settings.AUTH_USER_MODEL, verbose_name='R&D Penanggung Jawab')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui Oleh')),
            ],
            options={
                'verbose_name': 'Permintaan Pengembangan Produk',
                'verbose_name_plural': 'Permintaan Pengembangan Produk',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDevelopmentTrial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('trial_number', models.PositiveIntegerField(verbose_name='Percobaan Ke-')),
                ('trial_date', models.DateField(verbose_name='Tanggal Percobaan')),
                ('formulation', models.JSONField(default=dict, verbose_name='Formulasi (JSON)')),
                ('formulation_notes', models.TextField(blank=True, verbose_name='Catatan Formulasi')),
                ('results', models.JSONField(default=dict, verbose_name='Hasil Analisis (JSON)')),
                ('results_notes', models.TextField(blank=True, verbose_name='Catatan Hasil')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Evaluasi'), ('pass', 'Berhasil'), ('fail', 'Gagal')], default='pending', max_length=10, verbose_name='Status Trial')),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_trials', to=settings.AUTH_USER_MODEL, verbose_name='Dilakukan Oleh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='external_requests.productdevelopmentrequest', verbose_name='Proyek Pengembangan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui Oleh')),
            ],
            options={
                'verbose_name': 'Trial Pengembangan Produk',
                'verbose_name_plural': 'Trial Pengembangan Produk',
                'ordering': ['request', 'trial_number'],
                'unique_together': {('request', 'trial_number')},
            },
        ),
    ]
