# Generated by Django 6.0.4 on 2026-04-24 03:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versi')),
                ('version_label', models.CharField(blank=True, max_length=20, verbose_name='Label Versi')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Menunggu Persetujuan'), ('active', 'Aktif'), ('superseded', 'Diganti Versi Baru'), ('archived', 'Diarsipkan')], default='draft', max_length=20, verbose_name='Status')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Berlaku')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Berakhir')),
                ('revision_notes', models.TextField(blank=True, verbose_name='Catatan Revisi')),
                ('submitted_for_approval_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Pengajuan')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Persetujuan')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Alasan Penolakan')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_specs', to=settings.AUTH_USER_MODEL, verbose_name='Disetujui Oleh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specifications', to='samples.productcategory', verbose_name='Kategori Produk')),
                ('submitted_for_approval_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_specs', to=settings.AUTH_USER_MODEL, verbose_name='Diajukan Oleh')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui Oleh')),
            ],
            options={
                'verbose_name': 'Spesifikasi Produk',
                'verbose_name_plural': 'Spesifikasi Produk',
                'ordering': ['product_category', '-version'],
            },
        ),
        migrations.CreateModel(
            name='SpecificationLimit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Nilai Minimum')),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Nilai Maksimum')),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Nilai Target')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Satuan')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spec_limits', to='analysis.testparameter', verbose_name='Parameter')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='specifications.productspecification', verbose_name='Spesifikasi')),
            ],
            options={
                'verbose_name': 'Batas Spesifikasi',
                'verbose_name_plural': 'Batas Spesifikasi',
                'ordering': ['parameter__order'],
            },
        ),
        migrations.AddIndex(
            model_name='productspecification',
            index=models.Index(fields=['product_category', 'status'], name='specificati_product_e3ac37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together={('product_category', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='specificationlimit',
            unique_together={('specification', 'parameter')},
        ),
    ]
