# Generated by Django 6.0.4 on 2026-04-24 03:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Alat')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kode Alat')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Nomor Seri')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Produsen')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Lokasi')),
                ('last_calibration', models.DateField(blank=True, null=True, verbose_name='Kalibrasi Terakhir')),
                ('calibration_due', models.DateField(blank=True, null=True, verbose_name='Kalibrasi Berikutnya')),
                ('calibration_certificate', models.FileField(blank=True, null=True, upload_to='calibrations/', verbose_name='Sertifikat Kalibrasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui Oleh')),
            ],
            options={
                'verbose_name': 'Instrumen',
                'verbose_name_plural': 'Instrumen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Metode')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Kode Metode')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('standard_reference', models.CharField(blank=True, max_length=200, verbose_name='Referensi Standar')),
                ('is_accredited', models.BooleanField(default=False, verbose_name='Terakreditasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='methods', to='analysis.instrument', verbose_name='Instrumen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui Oleh')),
            ],
            options={
                'verbose_name': 'Metode Uji',
                'verbose_name_plural': 'Metode Uji',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('parameter_name', models.CharField(max_length=200, verbose_name='Nama Parameter')),
                ('parameter_code', models.CharField(blank=True, max_length=50, verbose_name='Kode Parameter')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Satuan')),
                ('result_type', models.CharField(choices=[('numeric', 'Numerik'), ('text', 'Teks'), ('pass_fail', 'Pass/Fail')], default='numeric', max_length=10, verbose_name='Tipe Hasil')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Wajib')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, verbose_name='Desimal')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan Tampil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameters', to='analysis.instrument', verbose_name='Instrumen')),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameters', to='analysis.testmethod', verbose_name='Metode Uji')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_parameters', to='samples.productcategory', verbose_name='Kategori Produk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui Oleh')),
            ],
            options={
                'verbose_name': 'Parameter Uji',
                'verbose_name_plural': 'Parameter Uji',
                'ordering': ['product_category', 'order', 'parameter_name'],
                'unique_together': {('product_category', 'parameter_name')},
            },
        ),
        migrations.CreateModel(
            name='AnalysisAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Penugasan')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Batas Waktu')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Analis')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Ditugaskan Oleh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='samples.sample', verbose_name='Sampel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui Oleh')),
                ('parameters', models.ManyToManyField(blank=True, related_name='assignments', to='analysis.testparameter', verbose_name='Parameter yang Ditugaskan')),
            ],
            options={
                'verbose_name': 'Penugasan Analisis',
                'verbose_name_plural': 'Penugasan Analisis',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('result_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Nilai Hasil (Numerik)')),
                ('result_text', models.CharField(blank=True, max_length=300, verbose_name='Nilai Hasil (Teks)')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Satuan')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Input'), ('submitted', 'Disubmit'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=10, verbose_name='Status')),
                ('pass_fail', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'N/A')], default='na', max_length=5, verbose_name='Pass/Fail')),
                ('spec_min', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Spec Min (Snapshot)')),
                ('spec_max', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Spec Max (Snapshot)')),
                ('spec_target', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Spec Target (Snapshot)')),
                ('spec_version', models.CharField(blank=True, max_length=20, verbose_name='Versi Spesifikasi')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Submit')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Persetujuan')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Alasan Penolakan')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan Analis')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_results', to=settings.AUTH_USER_MODEL, verbose_name='Disetujui Oleh')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analysis.analysisassignment', verbose_name='Penugasan')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_results', to=settings.AUTH_USER_MODEL, verbose_name='Disubmit Oleh')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='analysis.testparameter', verbose_name='Parameter')),
            ],
            options={
                'verbose_name': 'Hasil Analisis',
                'verbose_name_plural': 'Hasil Analisis',
                'ordering': ['assignment', 'parameter__order'],
                'indexes': [models.Index(fields=['status', 'pass_fail'], name='analysis_an_status_a8eac9_idx')],
                'unique_together': {('assignment', 'parameter')},
            },
        ),
        migrations.CreateModel(
            name='AnalysisChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('is_required', models.BooleanField(default=True, verbose_name='Wajib')),
                ('is_done', models.BooleanField(default=False, verbose_name='Selesai')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Diselesaikan Oleh')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_checklist', to='samples.sample', verbose_name='Sampel')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='analysis.testparameter', verbose_name='Parameter')),
            ],
            options={
                'verbose_name': 'Checklist Analisis',
                'verbose_name_plural': 'Checklist Analisis',
                'ordering': ['parameter__order'],
                'unique_together': {('sample', 'parameter')},
            },
        ),
    ]
