# Generated by Django 6.0.4 on 2026-04-24 03:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('complaint_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor Komplain')),
                ('source', models.CharField(choices=[('customer', 'Customer (Eksternal)'), ('internal', 'Internal')], max_length=10, verbose_name='Sumber Komplain')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Nama Customer')),
                ('customer_contact', models.CharField(blank=True, max_length=200, verbose_name='Kontak Customer')),
                ('product_description', models.CharField(blank=True, max_length=300, verbose_name='Deskripsi Produk')),
                ('batch_code', models.CharField(blank=True, max_length=100, verbose_name='Kode Batch')),
                ('description', models.TextField(verbose_name='Deskripsi Komplain')),
                ('complaint_category', models.CharField(blank=True, max_length=100, verbose_name='Kategori Komplain')),
                ('status', models.CharField(choices=[('open', 'Terbuka'), ('in_progress', 'Sedang Ditangani'), ('closed', 'Ditutup')], default='open', max_length=15, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi'), ('critical', 'Kritis')], default='medium', max_length=10, verbose_name='Prioritas')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Laporan')),
                ('investigation_notes', models.TextField(blank=True, verbose_name='Catatan Investigasi')),
                ('root_cause', models.TextField(blank=True, verbose_name='Akar Penyebab')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Penutupan')),
                ('attachments_notes', models.TextField(blank=True, verbose_name='Catatan Lampiran')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Ditugaskan Ke')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Ditutup Oleh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('related_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='samples.sample', verbose_name='Sampel Terkait')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Dilaporkan Oleh')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui Oleh')),
            ],
            options={
                'verbose_name': 'Komplain',
                'verbose_name_plural': 'Komplain',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('action_type', models.CharField(choices=[('corrective', 'Korektif (CA)'), ('preventive', 'Preventif (PA)')], max_length=12, verbose_name='Tipe Tindakan')),
                ('description', models.TextField(verbose_name='Deskripsi Tindakan')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Batas Waktu')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('status', models.CharField(choices=[('open', 'Terbuka'), ('in_progress', 'Sedang Dikerjakan'), ('verified', 'Diverifikasi'), ('closed', 'Ditutup')], default='open', max_length=15, verbose_name='Status')),
                ('effectiveness_check', models.TextField(blank=True, verbose_name='Verifikasi Efektivitas')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Verifikasi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_responsibilities', to=settings.AUTH_USER_MODEL, verbose_name='PIC')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui Oleh')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_capas', to=settings.AUTH_USER_MODEL, verbose_name='Diverifikasi Oleh')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='complaints.complaint', verbose_name='Komplain')),
            ],
            options={
                'verbose_name': 'CAPA',
                'verbose_name_plural': 'CAPA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='complaints/attachments/', verbose_name='File')),
                ('file_name', models.CharField(max_length=300, verbose_name='Nama File')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Keterangan')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Upload')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complaints.complaint', verbose_name='Komplain')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Diupload Oleh')),
            ],
            options={
                'verbose_name': 'Lampiran Komplain',
                'verbose_name_plural': 'Lampiran Komplain',
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'priority'], name='complaints__status_4fcfa3_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['reported_at'], name='complaints__reporte_15284a_idx'),
        ),
    ]
