# Generated by Django 6.0.4 on 2026-04-24 03:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kode')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Kategori Dokumen',
                'verbose_name_plural': 'Kategori Dokumen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ControlledDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('doc_number', models.CharField(max_length=100, unique=True, verbose_name='Nomor Dokumen')),
                ('title', models.CharField(max_length=300, verbose_name='Judul Dokumen')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versi')),
                ('version_label', models.CharField(blank=True, max_length=20, verbose_name='Label Versi')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Menunggu Persetujuan'), ('active', 'Aktif'), ('archived', 'Diarsipkan')], default='draft', max_length=20, verbose_name='Status')),
                ('file', models.FileField(upload_to='documents/', verbose_name='File Dokumen')),
                ('file_name', models.CharField(blank=True, max_length=300, verbose_name='Nama File Asli')),
                ('file_size_kb', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ukuran File (KB)')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Berlaku')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='Jadwal Review')),
                ('submitted_for_approval_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Pengajuan')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Persetujuan')),
                ('tags', models.CharField(blank=True, max_length=300, verbose_name='Tag')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL, verbose_name='Disetujui Oleh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('submitted_for_approval_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_documents', to=settings.AUTH_USER_MODEL, verbose_name='Diajukan Oleh')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui Oleh')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Dokumen Terkontrol',
                'verbose_name_plural': 'Dokumen Terkontrol',
                'ordering': ['category', 'doc_number', '-version'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version_label', models.CharField(max_length=20, verbose_name='Label Versi')),
                ('file', models.FileField(upload_to='documents/revisions/', verbose_name='File Lama')),
                ('file_name', models.CharField(blank=True, max_length=300, verbose_name='Nama File')),
                ('change_summary', models.TextField(blank=True, verbose_name='Ringkasan Perubahan')),
                ('revised_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Revisi')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='documents.controlleddocument', verbose_name='Dokumen')),
                ('revised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_revisions', to=settings.AUTH_USER_MODEL, verbose_name='Direvisi Oleh')),
            ],
            options={
                'verbose_name': 'Revisi Dokumen',
                'verbose_name_plural': 'Revisi Dokumen',
                'ordering': ['-revised_at'],
            },
        ),
        migrations.AddIndex(
            model_name='controlleddocument',
            index=models.Index(fields=['doc_number', 'status'], name='documents_c_doc_num_70408c_idx'),
        ),
        migrations.AddIndex(
            model_name='controlleddocument',
            index=models.Index(fields=['category', 'status'], name='documents_c_categor_0ba369_idx'),
        ),
    ]
