# Generated by Django 6.0.4 on 2026-04-24 03:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
            ],
            options={
                'verbose_name': 'Kategori Item',
                'verbose_name_plural': 'Kategori Item',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('item_code', models.CharField(max_length=50, unique=True, verbose_name='Kode Item')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Item')),
                ('cas_number', models.CharField(blank=True, max_length=50, verbose_name='Nomor CAS')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Supplier')),
                ('supplier_code', models.CharField(blank=True, max_length=100, verbose_name='Kode Supplier')),
                ('unit', models.CharField(max_length=30, verbose_name='Satuan')),
                ('min_stock', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Stok Minimum')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stok Saat Ini')),
                ('reorder_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Jumlah Reorder')),
                ('storage_condition', models.CharField(choices=[('room_temp', 'Suhu Ruang'), ('cold_4c', 'Dingin (2-8°C)'), ('freezer', 'Freezer (-20°C)'), ('dry', 'Tempat Kering'), ('flammable', 'Mudah Terbakar'), ('corrosive', 'Korosif')], default='room_temp', max_length=15, verbose_name='Kondisi Penyimpanan')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Lokasi Penyimpanan')),
                ('nearest_expired_date', models.DateField(blank=True, null=True, verbose_name='Kadaluarsa Terdekat')),
                ('expiry_alert_days', models.PositiveIntegerField(default=30, verbose_name='Alert Kadaluarsa (hari sebelumnya)')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_hazardous', models.BooleanField(default=False, verbose_name='Bahan Berbahaya (B3)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('related_instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='analysis.instrument', verbose_name='Instrumen Terkait')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui Oleh')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.itemcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Item Inventaris',
                'verbose_name_plural': 'Item Inventaris',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('quantity_requested', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Jumlah Diminta')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='Satuan')),
                ('reason', models.TextField(verbose_name='Alasan Permintaan')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('ordered', 'Sudah Dipesan'), ('received', 'Sudah Diterima'), ('rejected', 'Ditolak'), ('cancelled', 'Dibatalkan')], default='pending', max_length=10, verbose_name='Status')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='Auto-generated dari Alert')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Persetujuan')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Alasan Penolakan')),
                ('ordered_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Pemesanan')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Penerimaan')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Disetujui Oleh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='inventory.inventoryitem', verbose_name='Item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui Oleh')),
            ],
            options={
                'verbose_name': 'Permintaan Pembelian',
                'verbose_name_plural': 'Permintaan Pembelian',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('in', 'Masuk'), ('out', 'Keluar / Pemakaian'), ('adjustment', 'Penyesuaian'), ('disposed', 'Dibuang')], max_length=12, verbose_name='Tipe Pergerakan')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Jumlah')),
                ('stock_before', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Stok Sebelum')),
                ('stock_after', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Stok Setelah')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='Satuan')),
                ('lot_number', models.CharField(blank=True, max_length=100, verbose_name='Nomor Lot')),
                ('expired_date', models.DateField(blank=True, null=True, verbose_name='Kadaluarsa Lot')),
                ('certificate_of_analysis', models.FileField(blank=True, null=True, upload_to='coa_reagents/', verbose_name='COA Supplier')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='Tipe Referensi')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='ID Referensi')),
                ('reference_notes', models.CharField(blank=True, max_length=300, verbose_name='Keterangan Referensi')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem', verbose_name='Item')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Dilakukan Oleh')),
            ],
            options={
                'verbose_name': 'Pergerakan Stok',
                'verbose_name_plural': 'Pergerakan Stok',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['item_code'], name='inventory_i_item_co_d93027_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category', 'is_active'], name='inventory_i_categor_83e0f2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'performed_at'], name='inventory_s_item_id_dbd279_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='inventory_s_movemen_018f99_idx'),
        ),
    ]
