# Generated by Django 6.0.4 on 2026-04-24 03:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FatBlendSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('production_date', models.DateField(verbose_name='Tanggal Produksi')),
                ('week_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minggu Ke-')),
                ('day_of_week', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hari (1=Senin)')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
            ],
            options={
                'verbose_name': 'Detail Fat Blend',
                'verbose_name_plural': 'Detail Fat Blend',
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Kode Line')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Line')),
                ('product_types', models.CharField(blank=True, max_length=200, verbose_name='Jenis Produk')),
                ('packaging_types', models.CharField(blank=True, max_length=200, verbose_name='Jenis Kemasan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Line Produksi',
                'verbose_name_plural': 'Line Produksi',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Tipe')),
                ('code', models.CharField(choices=[('raw_material', 'Raw Material'), ('fat_blend', 'Fat Blend'), ('finished_product', 'Finished Product'), ('packaging', 'Packaging')], max_length=30, unique=True, verbose_name='Kode')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Tipe Sampel',
                'verbose_name_plural': 'Tipe Sampel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinishedProductSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('target_smp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Target SMP (°C)')),
                ('target_iv', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Target IV (g I₂/100g)')),
                ('is_wo_override', models.BooleanField(default=False, verbose_name='WO Override Spesifikasi')),
                ('wo_notes', models.TextField(blank=True, verbose_name='Catatan Work Order')),
                ('fat_blends', models.ManyToManyField(blank=True, related_name='finished_products', to='samples.fatblendsample', verbose_name='Fat Blend yang Digunakan')),
            ],
            options={
                'verbose_name': 'Detail Finished Product',
                'verbose_name_plural': 'Detail Finished Product',
            },
        ),
        migrations.CreateModel(
            name='FinishedProductAdditive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('additive_type', models.CharField(choices=[('antioxidant', 'Antioksidan'), ('vitamin', 'Vitamin'), ('flavor', 'Flavor'), ('water', 'Air'), ('salt', 'Garam'), ('emulsifier', 'Emulsifier'), ('color', 'Pewarna'), ('preservative', 'Pengawet'), ('other', 'Lainnya')], max_length=15, verbose_name='Tipe Additive')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Bahan')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Jumlah')),
                ('unit', models.CharField(max_length=20, verbose_name='Satuan')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Catatan')),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additives', to='samples.finishedproductsample', verbose_name='Finished Product')),
            ],
            options={
                'verbose_name': 'Additive Finished Product',
                'verbose_name_plural': 'Additive Finished Product',
                'ordering': ['additive_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kode')),
                ('oil_variant', models.CharField(blank=True, choices=[('normal', 'Normal'), ('low_ge', 'Low GE')], max_length=10, verbose_name='Varian Minyak')),
                ('stearin_type', models.CharField(blank=True, choices=[('hard', 'Hard (Bulk)'), ('soft', 'Soft')], max_length=10, verbose_name='Tipe Stearin')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui Oleh')),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='samples.sampletype', verbose_name='Tipe Sampel')),
            ],
            options={
                'verbose_name': 'Kategori Produk',
                'verbose_name_plural': 'Kategori Produk',
                'ordering': ['sample_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='finishedproductsample',
            name='packaging_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_products_packaging', to='samples.productcategory', verbose_name='Jenis Kemasan'),
        ),
        migrations.AddField(
            model_name='fatblendsample',
            name='production_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fat_blend_samples', to='samples.productionline', verbose_name='Line Produksi'),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('sample_id', models.CharField(max_length=100, unique=True, verbose_name='ID Sampel')),
                ('sample_name', models.CharField(max_length=300, verbose_name='Nama Sampel')),
                ('status', models.CharField(choices=[('registered', 'Terdaftar'), ('in_analysis', 'Sedang Dianalisis'), ('completed', 'Analisis Selesai'), ('released', 'Dirilis'), ('rejected', 'Ditolak')], default='registered', max_length=20, verbose_name='Status')),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('rush', 'Rush')], default='normal', max_length=10, verbose_name='Urgensi')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Waktu Registrasi')),
                ('work_order', models.CharField(blank=True, max_length=100, verbose_name='Nomor Work Order')),
                ('batch_code', models.CharField(blank=True, max_length=100, verbose_name='Kode Batch/Produksi')),
                ('customer', models.CharField(blank=True, max_length=200, verbose_name='Customer / Requester')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Rilis')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='samples.productcategory', verbose_name='Kategori Produk')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_samples', to=settings.AUTH_USER_MODEL, verbose_name='Didaftarkan Oleh')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_samples', to=settings.AUTH_USER_MODEL, verbose_name='Dirilis Oleh')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui Oleh')),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='samples.sampletype', verbose_name='Tipe Sampel')),
            ],
            options={
                'verbose_name': 'Sampel',
                'verbose_name_plural': 'Sampel',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddField(
            model_name='finishedproductsample',
            name='sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finished_product_detail', to='samples.sample', verbose_name='Sampel'),
        ),
        migrations.AddField(
            model_name='fatblendsample',
            name='sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fat_blend_detail', to='samples.sample', verbose_name='Sampel'),
        ),
        migrations.CreateModel(
            name='StorageTank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kode Tangki')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Tangki')),
                ('tank_type', models.CharField(choices=[('storage', 'Tangki Utama (J)'), ('production', 'Tangki Produksi (T)')], max_length=15, verbose_name='Tipe Tangki')),
                ('capacity_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Kapasitas (Ton)')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Lokasi')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('current_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanks', to='samples.productcategory', verbose_name='Produk Saat Ini')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui Oleh')),
            ],
            options={
                'verbose_name': 'Tangki Penyimpanan',
                'verbose_name_plural': 'Tangki Penyimpanan',
                'ordering': ['tank_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('fill_sequence', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pengisian Ke-')),
                ('fill_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Pengisian')),
                ('transfer_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Permintaan Transfer')),
                ('transfer_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Persetujuan Transfer')),
                ('transfer_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Transfer Disetujui Oleh')),
                ('transfer_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to=settings.AUTH_USER_MODEL, verbose_name='Transfer Diminta Oleh')),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_detail', to='samples.sample', verbose_name='Sampel')),
                ('destination_tank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_samples', to='samples.storagetank', verbose_name='Tangki Tujuan (T)')),
                ('source_tank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_samples', to='samples.storagetank', verbose_name='Tangki Asal (J)')),
            ],
            options={
                'verbose_name': 'Detail Raw Material',
                'verbose_name_plural': 'Detail Raw Material',
            },
        ),
        migrations.CreateModel(
            name='FatBlendComposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('proportion_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Proporsi (%)')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Catatan')),
                ('fat_blend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='samples.fatblendsample', verbose_name='Fat Blend')),
                ('raw_material_sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_fat_blends', to='samples.sample', verbose_name='Sampel Raw Material')),
            ],
            options={
                'verbose_name': 'Komposisi Fat Blend',
                'verbose_name_plural': 'Komposisi Fat Blend',
                'unique_together': {('fat_blend', 'raw_material_sample')},
            },
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['sample_type', 'status'], name='samples_sam_sample__9ec0c3_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['registered_at'], name='samples_sam_registe_87949f_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['urgency', 'status'], name='samples_sam_urgency_b95705_idx'),
        ),
    ]
