# Generated by Django 6.0.4 on 2026-04-24 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nama Template')),
                ('report_type', models.CharField(choices=[('coa', 'Certificate of Analysis (COA)'), ('internal_report', 'Laporan Internal'), ('complaint_report', 'Laporan Komplain'), ('spec_report', 'Laporan Spesifikasi'), ('inventory_report', 'Laporan Inventaris'), ('audit_report', 'Laporan Audit')], max_length=20, verbose_name='Tipe Laporan')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='report_templates/', verbose_name='File Template')),
                ('header_html', models.TextField(blank=True, verbose_name='Header HTML')),
                ('footer_html', models.TextField(blank=True, verbose_name='Footer HTML')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default untuk Tipe Ini')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Template Laporan',
                'verbose_name_plural': 'Template Laporan',
                'ordering': ['report_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('coa', 'Certificate of Analysis (COA)'), ('internal_report', 'Laporan Internal'), ('complaint_report', 'Laporan Komplain'), ('spec_report', 'Laporan Spesifikasi'), ('inventory_report', 'Laporan Inventaris'), ('audit_report', 'Laporan Audit')], max_length=20, verbose_name='Tipe Laporan')),
                ('title', models.CharField(max_length=300, verbose_name='Judul Laporan')),
                ('source_model', models.CharField(blank=True, max_length=100, verbose_name='Model Sumber')),
                ('source_id', models.CharField(blank=True, max_length=100, verbose_name='ID Sumber')),
                ('file', models.FileField(blank=True, null=True, upload_to='generated_reports/', verbose_name='File Laporan')),
                ('file_name', models.CharField(blank=True, max_length=300, verbose_name='Nama File')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Generate')),
                ('parameters_used', models.JSONField(blank=True, default=dict, verbose_name='Parameter Filter yang Digunakan')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Di-generate Oleh')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='reports.reporttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Laporan yang Di-generate',
                'verbose_name_plural': 'Laporan yang Di-generate',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_display', models.CharField(blank=True, max_length=200, verbose_name='Nama Pengguna (snapshot)')),
                ('action', models.CharField(choices=[('create', 'Buat Baru'), ('update', 'Update'), ('delete', 'Hapus'), ('login', 'Login'), ('logout', 'Logout'), ('approve', 'Setujui'), ('reject', 'Tolak'), ('submit', 'Submit'), ('release', 'Rilis'), ('archive', 'Arsipkan'), ('transfer', 'Transfer'), ('upload', 'Upload'), ('download', 'Download')], max_length=10, verbose_name='Aksi')),
                ('app_label', models.CharField(blank=True, max_length=50, verbose_name='App')),
                ('model_name', models.CharField(max_length=100, verbose_name='Nama Model')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='ID Objek')),
                ('object_repr', models.CharField(blank=True, max_length=500, verbose_name='Representasi Objek')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Perubahan')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Data Tambahan')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Session Key')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Waktu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='reports_aud_user_id_7a10fa_idx'), models.Index(fields=['model_name', 'object_id'], name='reports_aud_model_n_dc47ea_idx'), models.Index(fields=['action', 'timestamp'], name='reports_aud_action_6c25e2_idx'), models.Index(fields=['app_label', 'model_name'], name='reports_aud_app_lab_9631b2_idx')],
            },
        ),
    ]
